### ISSUE TITLE
2022Q3 Plan

### ISSUE THREAD

**Issue by haibing-wang** [arextest/deployments#1]
##### Arex = Postman + Document + JMeter + Data Mocker
* Arex is an API autotesting platform for debug and testing APIs. 
* Simplify and speed up API testing
* Minimize API testing costs

#### Feature
1. 100% Fully automated regression test
2. Easy API debugging during development
3. 100% Production problem debugging
4. Automatically generate test cases based on real requests
5. Support for CI
6. Autogenerate JSON-Schema

#### Roadmap
* Opensource communication
    * [ ] WebSite homepage
    * [ ] Github
    * [ ] Dockerhub
    * [ ] Twitter 
    * [ ] Youtube
    * [ ] Mail List
* Record-Replay Support Language
    * [x] Java (Record and replay with Agent)
	* [ ] Golang
	* [ ] Nodejs
* General Testing
    * [ ] Chrome plugin
    * [x] Single Request
	* [ ] AUTH
	* [x] Result Assert
	* [ ] Exploratory Testing
	* [x] Multi-Request reslt Compare
	* [ ] Test Static
* Arex Testing
    * [x] Record-Replay-Analysis
	* [x] Result analysis and Report
	* [x] Template (options of yaml/json format)
	* [ ] Github Action (CI/CD)
	* [x] Arex Dashboard
	* [ ] Mocker Data Edit
	* [ ] Generate Testcases and Assert
	* [ ] AUTH
	* [x] Share and Cooprate
* API Document
    * [x] Response Json-Schema Generate 
    * [ ] Request Json-Schema Generate 
    * [ ] Json-Schema Merge
    * [ ] Json-Schema Valid API
* UI
    * [x] WEB GUI
	* [ ] VSCode plugins
	* [x] Commander

**Comment by haibing-wang** [comment]
## WebSite homepage

### features
- [ ] homepage
- [ ] user login 
- [ ] user admin
- [ ] user work spaces / cases / documents
